name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Create build directory
        run: mkdir -p build

      - name: Copy assets
        run: cp -r assets build/

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o build/main main.go

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FedoraInstaller-${{ env.VERSION }}b
          path: build
