name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Create build directory
        run: mkdir -p build

      - name: Copy assets
        run: cp -r assets build/

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o build/main ./...

      - name: Test
        run: go test -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-build
          path: ./build/main

      - name: Create Release
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          draft: false
          prerelease: false
          body: ""

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: main-build
          path: ./build

      - name: Upload build artifact
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/main
          asset_name: main-${{ env.VERSION }}
          asset_content_type: application/octet-stream
