name: Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Create build directory
        run: mkdir -p build
      - name: Copy assets
        run: cp -r assets build/
      - name: Get version
        id: get_version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -v -o build/FedoraInstaller main.go
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FedoraInstaller-${{ env.VERSION }}
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: FedoraInstaller-${{ needs.build.outputs.version }}
          path: ./build
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.build.outputs.version }}"
          name: "v${{ needs.build.outputs.version }}"
          files: |
            ./build/FedoraInstaller
